const KEY="voledge_records_v1";let records=JSON.parse(localStorage.getItem(KEY)||"[]"),selectedId=null,screenshotData="",deferredPrompt=null;
const $=id=>document.getElementById(id),D=s=>s?new Date(s+"T00:00:00"):null,days=(a,b)=>a&&b?Math.round((D(b)-D(a))/864e5):null,fmt=n=>Number.isFinite(+n)?Number(n).toFixed(2):"—",pct=n=>Number.isFinite(+n)?`${Number(n).toFixed(1)}%`:"—",money=n=>Number.isFinite(+n)?new Intl.NumberFormat("es-ES",{style:"currency",currency:"USD"}).format(+n):"—";
function calc(r){const mid=((+r.callBid+ +r.callAsk)/2)+((+r.putBid+ +r.putAsk)/2),spread=(+r.callAsk-+r.callBid)+(+r.putAsk-+r.putBid),spreadRel=mid?spread/mid:0,costRel=+r.underlyingPrice?mid/+r.underlyingPrice:0,cd=days(r.moverDate,r.moocherDate),eb=days(r.exitDate,r.expiryDate);
const cal=cd>=5&&cd<=12?20:((cd>=3&&cd<=4)||(cd>=13&&cd<=18))?15:(cd===2||(cd>=19&&cd<=25))?8:2,exp=eb>=5&&eb<=15?10:(eb>=3&&eb<=21?7:3),iv=+r.iv<60?10:+r.iv<80?8:+r.iv<100?6:+r.iv<120?3:1,ivhv=+r.ivhv<90?10:+r.ivhv<=110?9:+r.ivhv<=125?7:+r.ivhv<=150?4:1,corr=Math.round((+r.correlation||0)*20),react=(+r.reaction||0)*2,liq=spreadRel<=.08?20:spreadRel<=.15?16:spreadRel<=.25?10:spreadRel<=.4?4:0,score=cal+exp+iv+ivhv+corr+react+liq,classification=score>=85?"Excelente":score>=70?"Buena":score>=55?"Regular":"Descartar",pnl=(r.entryPrice&&r.exitPrice)?((+r.exitPrice-+r.entryPrice)*100*(+r.contracts||1)):null;return{mid,spread,spreadRel,costRel,cd,eb,score,classification,pnl}}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function save(){localStorage.setItem(KEY,JSON.stringify(records));renderAll()}
function renderAll(){renderDashboard();renderCalendar();renderJournal()}
function renderDashboard(){const q=$("searchInput").value.toLowerCase(),st=$("statusFilter").value,cl=$("classFilter").value,sort=$("sortSelect").value;let arr=records.filter(r=>{const c=calc(r),hay=`${r.moocher} ${r.moocherTicker} ${r.mover} ${r.moverTicker} ${r.sector}`.toLowerCase();return(!q||hay.includes(q))&&(!st||r.status===st)&&(!cl||c.classification===cl)});
arr.sort((a,b)=>{const ca=calc(a),cb=calc(b);if(sort==="score-desc")return cb.score-ca.score;if(sort==="moverDate-asc")return D(a.moverDate)-D(b.moverDate);if(sort==="exitDate-asc")return D(a.exitDate)-D(b.exitDate);if(sort==="ivhv-asc")return +a.ivhv-+b.ivhv;return ca.spreadRel-cb.spreadRel});
$("opportunityGrid").innerHTML=arr.map(r=>{const c=calc(r),klass=c.classification.toLowerCase();return`<article class="card opportunity-card" onclick="showDetail('${r.id}')"><div class="card-top"><div><div class="ticker">${esc(r.moocherTicker)}</div><div class="pair-line">${esc(r.moocher)} ← ${esc(r.moverTicker)}</div></div><div class="score-badge">${c.score}</div></div><div class="badges"><span class="pill ${klass}">${c.classification}</span><span class="pill neutral">${esc(r.status||"Vigilar")}</span></div><div class="mini-grid"><div><span>IV</span><strong>${pct(r.iv)}</strong></div><div><span>VI/HV</span><strong>${pct(r.ivhv)}</strong></div><div><span>Straddle medio</span><strong>$${fmt(c.mid)}</strong></div><div><span>Spread relativo</span><strong>${pct(c.spreadRel*100)}</strong></div></div><div class="risk-line">Mover ${r.moverDate} · Salida ${r.exitDate}</div></article>`}).join("");
const cs=records.map(calc),pnl=cs.reduce((s,x)=>s+(x.pnl||0),0);$("kpiTotal").textContent=records.length;$("kpiExcellent").textContent=cs.filter(x=>x.classification==="Excelente").length;$("kpiOpen").textContent=records.filter(r=>r.status==="Abierta").length;$("kpiPnl").textContent=money(pnl);$("resultsCount").textContent=`${arr.length} resultados`;$("heroScore").textContent=cs.length?Math.max(...cs.map(x=>x.score)):"—"}
function renderCalendar(){const ev=[];records.forEach(r=>{ev.push({date:r.moverDate,type:"Mover",title:`${r.moverTicker} publica`,sub:`Impacto potencial sobre ${r.moocherTicker}`},{date:r.exitDate,type:"Salida",title:`Cerrar ${r.moocherTicker}`,sub:"Fecha máxima orientativa"},{date:r.moocherDate,type:"Moocher",title:`${r.moocherTicker} publica`,sub:"Evitar permanecer expuesto al evento propio"})});ev.sort((a,b)=>D(a.date)-D(b.date));$("calendarList").innerHTML=ev.map(e=>`<article class="card event-card"><div class="event-date">${e.date}</div><div class="event-main"><strong>${esc(e.title)}</strong><span>${esc(e.sub)}</span></div><div class="event-tag">${e.type}</div></article>`).join("")}
function renderJournal(){$("journalBody").innerHTML=records.map(r=>{const c=calc(r),pc=c.pnl==null?"":c.pnl>=0?"pnl-positive":"pnl-negative";return`<tr><td><strong>${esc(r.moocherTicker)}/${esc(r.moverTicker)}</strong></td><td>${esc(r.status||"")}</td><td>${r.entryPrice?money(+r.entryPrice*100*(+r.contracts||1)):"—"}</td><td>${r.exitPrice?money(+r.exitPrice*100*(+r.contracts||1)):"—"}</td><td class="${pc}">${c.pnl==null?"—":money(c.pnl)}</td><td>${c.score}</td></tr>`}).join("")}
window.showDetail=id=>{selectedId=id;const r=records.find(x=>x.id===id);if(!r)return;const c=calc(r),metric=(a,b)=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`,pc=c.pnl==null?"":c.pnl>=0?"pnl-positive":"pnl-negative";$("detailPanel").classList.remove("hidden");$("detailTitle").textContent=`${r.moocherTicker} / ${r.moverTicker}`;$("detailContent").innerHTML=`<div class="detail-grid">${metric("Score",`${c.score}/100 · ${c.classification}`)}${metric("Coste medio",`$${fmt(c.mid)} · $${fmt(c.mid*100)}/contrato`)}${metric("Spread relativo",pct(c.spreadRel*100))}${metric("Coste / acción",pct(c.costRel*100))}${metric("Días entre resultados",c.cd??"—")}${metric("Buffer vencimiento",c.eb??"—")}${metric("Volatilidad",`IV ${pct(r.iv)} · VI/HV ${pct(r.ivhv)}`)}${metric("Correlación",fmt(r.correlation))}${metric("Strike / vencimiento",`${fmt(r.strike)} · ${r.expiryDate}`)}${metric("Estado",esc(r.status||"Vigilar"))}${metric("Entrada / salida",`${r.entryPrice?"$"+fmt(r.entryPrice):"—"} / ${r.exitPrice?"$"+fmt(r.exitPrice):"—"}`)}<div class="metric"><span>P&L realizado</span><strong class="${pc}">${c.pnl==null?"—":money(c.pnl)}</strong></div></div>${r.notes?`<div class="notes-box">${esc(r.notes)}</div>`:""}${r.screenshot?`<img src="${r.screenshot}" class="detail-image">`:""}`;$("detailPanel").scrollIntoView({behavior:"smooth"})}
function openForm(r=null){$("operationForm").reset();screenshotData="";$("recordId").value=r?.id||"";$("dialogTitle").textContent=r?"Editar operación":"Nueva operación";const ids=["moocher","moocherTicker","mover","moverTicker","sector","moverDate","moocherDate","exitDate","underlyingPrice","expiryDate","strike","callBid","callAsk","putBid","putAsk","iv","ivhv","correlation","reaction","status","entryPrice","exitPrice","contracts","notes"];ids.forEach(id=>{if(r&&r[id]!=null)$(id).value=r[id]});screenshotData=r?.screenshot||"";$("screenshotPreview").src=screenshotData;$("screenshotPreview").classList.toggle("hidden",!screenshotData);updateLiveScore();$("operationDialog").showModal()}
function getForm(){const ids=["moocher","moocherTicker","mover","moverTicker","sector","moverDate","moocherDate","exitDate","underlyingPrice","expiryDate","strike","callBid","callAsk","putBid","putAsk","iv","ivhv","correlation","reaction","status","entryPrice","exitPrice","contracts","notes"],r={};ids.forEach(id=>r[id]=$(id).value);r.id=$("recordId").value||crypto.randomUUID();r.screenshot=screenshotData;return r}
function updateLiveScore(){try{const c=calc(getForm());$("liveScore").textContent=`Score estimado: ${c.score}/100 · ${c.classification}`}catch{}}
$("operationForm").addEventListener("input",updateLiveScore);$("operationForm").addEventListener("submit",e=>{e.preventDefault();const r=getForm(),i=records.findIndex(x=>x.id===r.id);if(i>=0)records[i]=r;else records.push(r);save();$("operationDialog").close();showDetail(r.id)});$("screenshot").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{screenshotData=rd.result;$("screenshotPreview").src=screenshotData;$("screenshotPreview").classList.remove("hidden")};rd.readAsDataURL(f)});
$("newBtn").onclick=()=>openForm();$("closeDialog").onclick=$("cancelBtn").onclick=()=>$("operationDialog").close();$("editBtn").onclick=()=>openForm(records.find(x=>x.id===selectedId));$("deleteBtn").onclick=()=>{if(selectedId&&confirm("¿Eliminar esta operación?")){records=records.filter(x=>x.id!==selectedId);selectedId=null;$("detailPanel").classList.add("hidden");save()}};
["searchInput","statusFilter","classFilter","sortSelect"].forEach(id=>$(id).addEventListener("input",renderDashboard));document.querySelectorAll(".mobile-nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".mobile-nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(b.dataset.view+"View").classList.add("active");scrollTo({top:0,behavior:"smooth"})});
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(records,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="voledge-data.json";a.click();URL.revokeObjectURL(a.href)};$("importInput").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{records=JSON.parse(rd.result);save();alert("Datos importados.")}catch{alert("JSON no válido.")}};rd.readAsText(f)});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").hidden=true};if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
if(!records.length){records=[{id:crypto.randomUUID(),moocher:"ON Semiconductor",moocherTicker:"ON",mover:"Texas Instruments",moverTicker:"TXN",sector:"Semiconductores",moverDate:"2026-07-22",moocherDate:"2026-07-31",exitDate:"2026-07-30",underlyingPrice:"92.15",expiryDate:"2026-08-07",strike:"92",callBid:"7.35",callAsk:"10.10",putBid:"8.25",putAsk:"10.30",iv:"92.2",ivhv:"96.2",correlation:"0.75",reaction:"4",status:"Vigilar",contracts:"1",notes:"Par destacado por UBS. Usar orden limitada."},{id:crypto.randomUUID(),moocher:"Microchip",moocherTicker:"MCHP",mover:"Texas Instruments",moverTicker:"TXN",sector:"Semiconductores",moverDate:"2026-07-22",moocherDate:"2026-07-28",exitDate:"2026-07-27",underlyingPrice:"84.53",expiryDate:"2026-08-07",strike:"84",callBid:"7.00",callAsk:"7.80",putBid:"5.90",putAsk:"6.80",iv:"74.2",ivhv:"112.5",correlation:"0.78",reaction:"5",status:"Preparada",contracts:"1",notes:"Calendario corto y buena ejecución relativa."},{id:crypto.randomUUID(),moocher:"indie Semiconductor",moocherTicker:"INDI",mover:"NXP Semiconductors",moverTicker:"NXPI",sector:"Semiconductores automoción",moverDate:"2026-07-28",moocherDate:"2026-08-06",exitDate:"2026-08-05",underlyingPrice:"4.18",expiryDate:"2026-08-21",strike:"4",callBid:"0.65",callAsk:"0.80",putBid:"0.40",putAsk:"0.60",iv:"115.1",ivhv:"111.6",correlation:"0.68",reaction:"4",status:"Vigilar",contracts:"1",notes:"IV absoluta alta; vigilar coste relativo."}];save()}else renderAll();
